import * as THREE from 'three';
import { OrbitControls } from 'three/addons/controls/OrbitControls.js';
import { compare,cost,evaluate,key,levels,type Item,type Point,type Template } from './model';
import './style.css';
import { installUX } from './ux';
let ui: ReturnType<typeof installUX> | undefined;
let freePlacement=false, cursorPosition:Point=[0,0,0];

const app=document.querySelector<HTMLDivElement>('#app')!;
app.innerHTML=`<div id="viewport"></div><h2 id="heading"></h2><p id="hint"></p><div id="status"></div><div id="score"></div><div id="local"></div><select id="level"></select><select id="mode"><option value="build">Level construction</option><option value="template">Template workbench</option></select><select id="tool"><option value="block">Fixed block</option><option value="socket">Input socket</option><option value="instance">Template instance</option></select><select id="turn"><option value="0">0°</option><option value="1">90°</option><option value="2">180°</option><option value="3">270°</option></select><select id="template"></select><select id="instance"></select><select id="input"><option value="">Single block</option></select><input id="plane" type="number" value="0"><input id="name" value="New shape"><button id="undo">Undo</button><button id="redo">Redo</button><button id="diff">Diff: on</button><button id="reset">Clear workspace</button><button id="preview">Preview: output</button><button id="new">New template</button><button id="rename">Rename</button><button id="export">Export library</button><button id="import">Import library</button><input id="file" type="file" accept="application/json" hidden>`;
const el=<T extends HTMLElement>(id:string)=>document.getElementById(id) as T;
let level=0,items:Item[]=[],templates:Template[]=[],showDiff=true,markers=false;
try { const saved=JSON.parse(localStorage.getItem('formsmith-v1')??'null');if(saved){templates=saved.templates??[];items=saved.items??[];level=saved.level??0;if(!levels[level])level=0;evaluate(items,templates);} } catch {templates=[];items=[];}
const mode=()=>el<HTMLSelectElement>('mode').value;
const selected=()=>templates.find(t=>t.id===el<HTMLSelectElement>('template').value);
const editing=()=>mode()==='template'?selected()?.items??[]:items;
const state=()=>JSON.stringify({items,templates,level});
let undo:string[]=[],redo:string[]=[];
function save(){localStorage.setItem('formsmith-v1',state());}
function restore(s:string){const v=JSON.parse(s);items=v.items;templates=v.templates;level=v.level;shelf();draw();}
function mutate(fn:()=>void){const previous=state();try{fn();evaluate(items,templates);for(const t of templates)evaluate(t.items,templates);undo.push(previous);redo=[];save();draw();}catch(e){restore(previous);status((e as Error).message);}}
function status(s:string){el('status').textContent=s;}
function shelf(){const id=el<HTMLSelectElement>('template').value;const input=el<HTMLSelectElement>('input').value;for(const name of ['template','instance','input']){const s=el<HTMLSelectElement>(name);s.replaceChildren();if(name==='input')s.add(new Option('Single block',''));for(const t of templates)s.add(new Option(t.name,t.id));s.value=name==='input'?input:(templates.some(t=>t.id===id)?id:templates[0]?.id??'');}}
levels.forEach((l,i)=>el<HTMLSelectElement>('level').add(new Option(l.name,String(i))));shelf();

const scene=new THREE.Scene();scene.background=new THREE.Color('#101d28');
const renderer=new THREE.WebGLRenderer({antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.shadowMap.enabled=true;el('viewport').append(renderer.domElement);
const camera=new THREE.PerspectiveCamera(45,1,.1,150);camera.position.set(15,13,19);
const controls=new OrbitControls(camera,renderer.domElement);controls.target.set(0,2,0);controls.enableDamping=true;
scene.add(new THREE.HemisphereLight(0xcdeeff,0x263544,2.5));const light=new THREE.DirectionalLight(0xffffff,3);light.position.set(8,18,12);scene.add(light);
const targetGroup=new THREE.Group(),buildGroup=new THREE.Group();targetGroup.position.x=-9;buildGroup.position.x=3;scene.add(targetGroup,buildGroup);
const geometry=new THREE.BoxGeometry(.96,.96,.96);
const materials={block:new THREE.MeshStandardMaterial({color:0x72d9c3,roughness:.55}),target:new THREE.MeshStandardMaterial({color:0x8b9bad,roughness:.6}),extra:new THREE.MeshStandardMaterial({color:0xef807c}),missing:new THREE.MeshStandardMaterial({color:0x77b9f8,transparent:true,opacity:.25,wireframe:true}),socket:new THREE.MeshStandardMaterial({color:0xffbd69,transparent:true,opacity:.7})};
function cube(group:THREE.Object3D,p:Point,material:THREE.Material,index?:number){const mesh=new THREE.Mesh(geometry,material);mesh.position.set(...p);mesh.userData={index,point:p};group.add(mesh);return mesh;}
for(const group of [targetGroup,buildGroup]){const grid=new THREE.GridHelper(24,24,0x426176,0x263e4d);grid.position.y=-.5;scene.add(grid);grid.position.x=group.position.x;}
const plane=new THREE.Mesh(new THREE.PlaneGeometry(24,24),new THREE.MeshBasicMaterial({color:0x4895bf,transparent:true,opacity:.08,side:THREE.DoubleSide,depthWrite:false}));plane.rotation.x=-Math.PI/2;scene.add(plane);
const ghost=cube(scene,[0,0,0],new THREE.MeshBasicMaterial({color:0xffffff,wireframe:true}));ghost.visible=false;
const origin=new THREE.AxesHelper(2);origin.position.set(3,-.5,0);scene.add(origin);
const ghosts=new THREE.Group();ghosts.position.x=3;scene.add(ghosts);ghost.visible=false;
const ghostMaterial=new THREE.MeshBasicMaterial({color:0xb0ffe0,transparent:true,opacity:.4,depthWrite:false});
const gizmo=new THREE.Group();gizmo.visible=false;scene.add(gizmo);
const floatingGrid=new THREE.GridHelper(12,12,0x579ac0,0x284c60);floatingGrid.visible=false;scene.add(floatingGrid);
const directions=[new THREE.Vector3(1,0,0),new THREE.Vector3(0,1,0),new THREE.Vector3(0,0,1)];
directions.forEach((direction,axis)=>{const color=[0xf18083,0x8de2a6,0x76baff][axis];gizmo.add(new THREE.ArrowHelper(direction,new THREE.Vector3(),2.3,color,.35,.18));const handle=new THREE.Mesh(new THREE.SphereGeometry(.25),new THREE.MeshBasicMaterial({color,depthTest:false}));handle.position.copy(direction.clone().multiplyScalar(2.3));handle.userData.axis=axis;handle.renderOrder=5;gizmo.add(handle);});
let axisDrag:{axis:number;start:Point;mouse:[number,number];direction:[number,number];pixels:number}|null=null;
function placeAt(at:Point){const kind=el<HTMLSelectElement>('tool').value as Item['kind'];if(kind==='socket'&&mode()==='build'){status('Sockets belong inside a template.');return;}if(kind==='instance'&&!el<HTMLSelectElement>('instance').value){status('Choose a shape from the library.');return;}const item:Item={kind,position:[...at],turn:Number(el<HTMLSelectElement>('turn').value)};if(kind==='instance'){item.template=el<HTMLSelectElement>('instance').value;item.input=el<HTMLSelectElement>('input').value||undefined;}mutate(()=>editing().push(item));updateGhost();}
function updateGhost(){ghost.visible=false;ghosts.clear();if(ui?.erase())return;const at=freePlacement?cursorPosition:pending;if(!at)return;try{const kind=el<HTMLSelectElement>('tool').value as Item['kind'];let input:Point[]=[[0,0,0]];const inputId=el<HTMLSelectElement>('input').value;if(inputId)input=evaluate([{kind:'instance',template:inputId,position:[0,0,0],turn:0}],templates);const shape=evaluate([{kind,position:at,turn:Number(el<HTMLSelectElement>('turn').value),template:el<HTMLSelectElement>('instance').value,input:inputId||undefined}],templates,input);for(const p of shape)cube(ghosts,p,ghostMaterial);}catch{/* Invalid compositions are reported when placed. */}}
renderer.domElement.addEventListener('pointerdown',e=>{if(!freePlacement||ui?.erase()||e.button!==0)return;const r=renderer.domElement.getBoundingClientRect();pointer.set((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1);ray.setFromCamera(pointer,camera);const hit=ray.intersectObjects(gizmo.children,true).find(h=>h.object.userData.axis!==undefined);if(!hit)return;const axis=hit.object.userData.axis as number;const a=gizmo.position.clone().project(camera),b=gizmo.position.clone().add(directions[axis]).project(camera);const dx=(b.x-a.x)*r.width/2,dy=-(b.y-a.y)*r.height/2,pixels=Math.max(8,Math.hypot(dx,dy));axisDrag={axis,start:[...cursorPosition],mouse:[e.clientX,e.clientY],direction:[dx/pixels,dy/pixels],pixels};controls.enabled=false;renderer.domElement.setPointerCapture(e.pointerId);},{capture:true});
renderer.domElement.addEventListener('pointercancel',()=>{axisDrag=null;controls.enabled=true;});
function draw(){targetGroup.clear();buildGroup.clear();const template=selected();const inputId=el<HTMLSelectElement>('input').value;let supplied:Point[]=[[0,0,0]];try{if(inputId)supplied=evaluate([{kind:'instance',template:inputId,position:[0,0,0],turn:0}],templates);const output=evaluate(editing(),templates,supplied);const diff=compare(output,levels[level].target);if(mode()==='build'){for(const p of levels[level].target)cube(targetGroup,p,materials.target);const extra=new Set(diff.extra.map(key));for(const p of output)cube(buildGroup,p,showDiff&&extra.has(key(p))?materials.extra:materials.block);if(showDiff)for(const p of diff.missing)cube(buildGroup,p,materials.missing);el('heading').textContent='Construction';el('hint').textContent=levels[level].hint;const c=cost(items,templates);el('score').textContent=`${c.total} cost · ${c.direct} blocks + ${c.calls} calls + ${c.definitions} definitions`;el('local').textContent=[...c.local].map(id=>templates.find(t=>t.id===id)?.name).join(', ')||'No templates used yet';status(diff.missing.length===0&&diff.extra.length===0?'Complete! Try another level or improve your cost.':`${diff.correct.length}/${levels[level].target.length} correct · ${diff.missing.length} missing · ${diff.extra.length} extra`);}else{el('heading').textContent=template?.name??'Create a template';el('hint').textContent='Place fixed blocks and input sockets. The axes mark the shape origin.';if(markers){editing().forEach((i,index)=>cube(buildGroup,i.position,i.kind==='socket'?materials.socket:materials.block,index));}else for(const p of output)cube(buildGroup,p,materials.block);el('score').textContent=template?`Definition: ${8+template.items.length*2} · ${output.length} output voxels`:'';el('local').textContent='';status('Template workbench · Shift-click removes the source placement.');}}catch(e){status((e as Error).message);}plane.position.set(3,Number(el<HTMLInputElement>('plane').value)-.5,0);el<HTMLSelectElement>('level').value=String(level);el<HTMLButtonElement>('undo').disabled=!undo.length;el<HTMLButtonElement>('redo').disabled=!redo.length;updateGhost();}
const ray=new THREE.Raycaster(),pointer=new THREE.Vector2();let pending:Point|null=null,removeIndex=-1;
function pick(event:PointerEvent){const r=renderer.domElement.getBoundingClientRect();pointer.set((event.clientX-r.left)/r.width*2-1,-(event.clientY-r.top)/r.height*2+1);ray.setFromCamera(pointer,camera);const hits=ray.intersectObjects(buildGroup.children).filter(h=>h.object instanceof THREE.Mesh&&(h.object as THREE.Mesh).material!==materials.missing);pending=null;removeIndex=-1;if(hits.length){const h=hits[0];const p=h.object.userData.point as Point;const n=h.face!.normal;pending=[p[0]+Math.round(n.x),p[1]+Math.round(n.y),p[2]+Math.round(n.z)];removeIndex=editing().findLastIndex(i=>{if(i.kind==='instance')return evaluate([i],templates).some(q=>key(q)===key(p));if(i.kind==='socket'){let supplied:Point[]=[[0,0,0]];const id=el<HTMLSelectElement>('input').value;if(id)supplied=evaluate([{kind:'instance',template:id,position:[0,0,0],turn:0}],templates);return evaluate([i],templates,supplied).some(q=>key(q)===key(p));}return key(i.position)===key(p);});if(Number.isInteger(h.object.userData.index))removeIndex=h.object.userData.index;} if(event.altKey && removeIndex>=0)pending=[...editing()[removeIndex].position]; if(freePlacement||!hits.length){const h=ray.intersectObject(plane)[0];if(h)pending=[Math.round(h.point.x-3),Number(el<HTMLInputElement>('plane').value),Math.round(h.point.z)];}updateGhost();}
let down={x:0,y:0};renderer.domElement.addEventListener('pointermove',e=>{if(axisDrag){const d=axisDrag;const p:Point=[...d.start];p[d.axis]+=Math.round(((e.clientX-d.mouse[0])*d.direction[0]+(e.clientY-d.mouse[1])*d.direction[1])/d.pixels);ui?.updateCursor(p);}else pick(e);});renderer.domElement.addEventListener('pointerdown',e=>{down={x:e.clientX,y:e.clientY};});renderer.domElement.addEventListener('contextmenu',e=>e.preventDefault());renderer.domElement.addEventListener('pointerup',e=>{if(axisDrag){axisDrag=null;controls.enabled=true;return;}if(Math.hypot(e.clientX-down.x,e.clientY-down.y)>5||e.button===1)return;pick(e);if(mode()==='template'&&!selected()){status('Create a template first.');return;}if(ui?.erase()||e.shiftKey||e.button===2){if(removeIndex>=0)mutate(()=>editing().splice(removeIndex,1));return;}if(!pending)return;if(freePlacement){ui?.updateCursor(pending);return;}const kind=el<HTMLSelectElement>('tool').value as Item['kind'];if(kind==='socket'&&mode()==='build'){status('Input sockets belong on the template workbench.');return;}if(kind==='instance'&&!selected()){status('Create a template first.');return;}const item:Item={kind,position:[...pending],turn:Number(el<HTMLSelectElement>('turn').value)};if(kind==='instance'){item.template=el<HTMLSelectElement>('instance').value;item.input=el<HTMLSelectElement>('input').value||undefined;}mutate(()=>editing().push(item));});
el('undo').onclick=()=>{const s=undo.pop();if(s){redo.push(state());restore(s);save();}};el('redo').onclick=()=>{const s=redo.pop();if(s){undo.push(state());restore(s);save();}};
el('new').onclick=()=>{const name=el<HTMLInputElement>('name').value;if(!name?.trim())return;mutate(()=>templates.push({id:crypto.randomUUID(),name:name.trim(),items:[]}));shelf();el<HTMLSelectElement>('template').value=templates.at(-1)!.id;el<HTMLSelectElement>('mode').value='template';el<HTMLSelectElement>('tool').value='socket';draw();};
el('rename').onclick=()=>{const t=selected();if(!t)return;const name=el<HTMLInputElement>('name').value;if(name?.trim()){mutate(()=>t.name=name.trim());shelf();draw();}};
el('reset').onclick=()=>{mutate(()=>editing().splice(0));};el('diff').onclick=()=>{showDiff=!showDiff;el('diff').textContent=`Diff: ${showDiff?'on':'off'}`;draw();};el('preview').onclick=()=>{markers=!markers;el('preview').textContent=`Preview: ${markers?'sockets':'output'}`;draw();};
for(const id of ['mode','template','input','plane'])el(id).onchange=()=>draw();el('level').onchange=()=>mutate(()=>{level=Number(el<HTMLSelectElement>('level').value);items=[];});
el('export').onclick=()=>{const url=URL.createObjectURL(new Blob([JSON.stringify({version:1,templates},null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='formsmith-library.json';a.click();URL.revokeObjectURL(url);};el('import').onclick=()=>el<HTMLInputElement>('file').click();el('file').onchange=async()=>{const file=el<HTMLInputElement>('file').files?.[0];if(!file)return;try{const data=JSON.parse(await file.text());if(data.version!==1||!Array.isArray(data.templates))throw Error('Unsupported library file.');const imported:Template[]=data.templates;if(imported.length>200||new Set(imported.map(t=>t.id)).size!==imported.length)throw Error('Invalid library.');for(const t of imported){if(typeof t.id!=='string'||typeof t.name!=='string'||!Array.isArray(t.items)||t.items.length>20000)throw Error('Invalid template.');for(const i of t.items)if(!['block','socket','instance'].includes(i.kind)||!Array.isArray(i.position)||i.position.length!==3||!i.position.every(n=>Number.isSafeInteger(n)&&Math.abs(n)<=1000)||!Number.isInteger(i.turn))throw Error('Invalid placement.');evaluate(t.items,imported);}mutate(()=>{templates=imported;items=[];});shelf();draw();}catch(e){status((e as Error).message);}el<HTMLInputElement>('file').value='';};
document.addEventListener('keydown',e=>{if(['INPUT','SELECT','TEXTAREA'].includes((e.target as HTMLElement).tagName))return;if(e.key.toLowerCase()==='r'){const s=el<HTMLSelectElement>('turn');s.value=String((Number(s.value)+1)%4);}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'){e.preventDefault();el(e.shiftKey?'redo':'undo').click();}});
new ResizeObserver(()=>{const v=el('viewport');renderer.setSize(v.clientWidth,v.clientHeight);camera.aspect=v.clientWidth/v.clientHeight;camera.updateProjectionMatrix();}).observe(el('viewport'));
draw();ui=installUX({templates:()=>templates,draw,place:placeAt,cursor:(p,free)=>{cursorPosition=[...p];freePlacement=free;gizmo.visible=free;gizmo.position.set(p[0]+3,p[1],p[2]);floatingGrid.visible=free;floatingGrid.position.set(p[0]+3,p[1]-.5,p[2]);updateGhost();}});renderer.setAnimationLoop(()=>{controls.update();renderer.render(scene,camera);});







